### ISSUE TITLE
Android-esp32cam imageview problem

### ISSUE THREAD

**Issue by Patsjemoe** [GCY/Android-ESP32-CAM-MJPEG-Viewer#1]
Hi,
Program compiled  OK, connection is made with ESP32, but the imageview shows a ver slow flickering picture, I can see it is the right picture, but it pops up and disappears very fast
Any idea why this could be ?
Thanks in advance
best regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
it is not creating the image , get following error : 
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/BitmapFactory: sampleSize 1, isHardware 0, isMutable 0, prefColorType 4, requireUnpremultiplied 0
Any suggestions ?
regards
Ludo

**Comment by mhfikri** [comment]
Hi @Patsjemoe , could you please share how you fix it cause I'm getting the same problem here.
Thanks
